# Generated by Django 4.2.2 on 2023-10-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_dailydata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecompletion',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
